export const hazardItems = [
  { number: 1, name: 'workingAtHeight', label: 'Working at Height' },
  { number: 2, name: 'excavations', label: 'Excavations' },
  { number: 3, name: 'temporaryRestrictions', label: 'Temporary Restrictions (Airspace)' },
  { number: 4, name: 'fireHotWorks', label: 'Fire (Hot works etc.)' },
  { number: 5, name: 'dust', label: 'Dust' },
  { number: 6, name: 'taskEnvironment', label: 'Task Environment (light / Temp)' },
  { number: 7, name: 'groundObstruction', label: 'Ground Obstruction' },
  { number: 8, name: 'temporaryWorks', label: 'Temporary Works (Blade Repair)' },
  { number: 9, name: 'contactWithStationary', label: 'Contact with stationary object' },
  { number: 10, name: 'manualHandling', label: 'Manual Handling' },
  { number: 11, name: 'objectOverturning', label: 'Object overturning / collapsing' },
  { number: 12, name: 'servicesUnderAbove', label: 'Services (under / above ground)' },
  { number: 13, name: 'slipsTrips', label: 'Slips, trips & falls same level' },
  { number: 14, name: 'trafficMovingVehicles', label: 'Traffic / Moving Vehicles' },
  { number: 15, name: 'confinedSpaces', label: 'Confined Spaces' },
  { number: 16, name: 'electricity', label: 'Electricity (Power lines, Sub-Ter. KV)' },
  { number: 17, name: 'noise', label: 'Noise' },
  { number: 18, name: 'vibration', label: 'Vibration' },
  { number: 19, name: 'adverseWeather', label: 'Adverse weather (VFR Minimums)' },
  { number: 20, name: 'risksFromTask', label: 'Risks to you or others from task' },
  { number: 21, name: 'riskOfPollution', label: 'Risk of pollution to environment' },
  { number: 22, name: 'biologicalAgents', label: 'Biological Agents' },
  { number: 23, name: 'aerielHazards', label: 'Aeriel Hazards (Crop Dusters)' },
  { number: 24, name: 'unstableStructure', label: 'Unstable structure' },
  { number: 25, name: 'craneLifting', label: 'Crane / Lifting Operations' },
  { number: 26, name: 'wasteRemoval', label: 'Waste Removal' },
  { number: 27, name: 'exogenousFactors', label: 'Exogenous Factors (Stress /Fatigue)' },
  { number: 28, name: 'other1', label: 'Other (Specify)' },
  { number: 29, name: 'other2', label: 'Other (Specify)' }
] as const;
